name: Deploy to Lightsail

on:
  push:  # Trigger on push events
    branches:
      - main  # ... to `main` (this will trigger the workflow when a PR is merged to `main`, if branch protection rules are in place)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Deploy to AWS Lightsail
      - name: Deploy to AWS Lightsail
        run: |
          aws lightsail create-container-service-deployment \
            --service-name ${{ secrets.LIGHTSAIL_SERVICE_NAME }} \
            --container-deployments '[{"containerName": "'${{ secrets.ECR_REPOSITORY }}'", "image": "'${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest'"}]' \
            --region ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
