# This workflow is for running Prettier for code formatting on the code
name: Format with Prettier

# This section defines when the workflow should be triggered.
on:
  push: # Trigger when any code is pushed to the repository, to any branch

# Define the jobs that the workflow will execute.
jobs:
  prettify: # The name of the job.
    runs-on: ubuntu-latest # Use the latest Ubuntu environment for the job.

    # Define the sequence of steps that the job will perform.
    steps:
      # Step 1: Check out the code from your repository.
      - name: Checkout code
        uses: actions/checkout@v4 # Use the checkout action to clone your repository.
        with:
          ref: ${{ github.head_ref }}

      # Step 2: Check if code is formatted well or if changes need to occur.
      # - name: Pretty dry run
      #   uses: creyD/prettier_action@v4.3
      #   with:
      #     prettier_options: --check **/*.{js,md,json}
      #     dry: True

      # Step 3: Make the changes
      - name: Prettify
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,md,json}
