# This workflow is for running ESLint on your JavaScript code
name: Lint

# This section defines when the workflow should be triggered.
on:
  push:  # Trigger when any code is pushed to the repository, to any branch

# Define the jobs that the workflow will execute.
jobs:
  lint:  # The name of the job. 
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment for the job.

    # Define the sequence of steps that the job will perform.
    steps:
      # Step 1: Check out the code from your repository.
      - name: Checkout code
        uses: actions/checkout@v4  # Use the checkout action to clone your repository.

      # Step 2: Set up Node
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # Step 3: Install dependencies -- note that ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci

      # Step 4: Run ESLint & Prettier using the pre-built action
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true